### ISSUE TITLE
Looking forward to the code

### ISSUE THREAD

**Issue by yhshu** [shijx12/TransferNet#1]
TransferNet does not only integrate text and knowledge base, but also has some interpretability.
The high accuracy achieved with a small amount of training data on MetaQA is surprising.
I believe the framework is a great idea. Looking forward to viewing its source code. Thanks.

**Comment by shijx12** [comment]
Thanks for your interest. We are going to submit our paper and the codes will be released after the reviewing.

**Comment by luxuantao** [comment]
期待+1

**Comment by lixiangpengcs** [comment]
Me Too

**Comment by shijx12** [comment]
Code released. Thanks.
