### ISSUE TITLE
Link to MetaQA dataset doesn't work

### ISSUE THREAD

**Issue by dungtn** [shijx12/TransferNet#4]
Hi @shijx12, congrats on the paper acceptance, and see you at EMNLP next week!

Is it possible to share/change the permission of the Google Drive link to the dataset? I've sent a request, but it might be easier for everyone to download it with public access?

Cheers :-)

**Comment by shijx12** [comment]
Sure. We will upload the data to Tsinghua Cloud and share the links.

**Comment by ShulinCao** [comment]
https://cloud.tsinghua.edu.cn/f/06d522c2ab384c789f0b/?dl=1 You can refer to the link here.
