### ISSUE TITLE
KVMemNN(EMNLP 2016)在MetaQA数据集上的结果

### ISSUE THREAD

**Issue by lys-github** [shijx12/TransferNet#7]
在论文中KVMemNN(EMNLP 2016)在MetaQA数据集1-hop/2-hop/3-hop的结果(95.8/25.1/10.1) 与PullNet的结果(96.2/82.7/48.9)不同，请问您是怎么得到的呢？

**Comment by shijx12** [comment]
我是参照提出MetaQA数据集的论文《Variational Reasoning for Question Answering with Knowledge Graph》中Table 1的结果
